#!/usr/bin/env python3
"""Regenerate patches/qt6wayland/0001-*.patch from the pristine qtwayland source.

Run inside the Debian machine after `make qt6wayland-dirclean qt6wayland-extract`:
    python3 <repo>/tools/gen-qt6wayland-patch.py ~/br/output/build/qt6wayland-6.11.1
The edits: wl_seat version 4 -> 5 with wl_pointer.frame events; wl_data_device_manager (and the
data source / offer / device objects) version 1 -> 3.  See PLAN.md for why.
"""
import os, shutil, subprocess, sys, tempfile

src = sys.argv[1]
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "patches", "qt6wayland",
                   "0001-compositor-wl_seat-v5-and-wl_data_device_manager-v3.patch")
CA = "src/compositor/compositor_api/"
WW = "src/compositor/wayland_wrapper/"
files = [CA + "qwaylandseat.cpp", CA + "qwaylandpointer.cpp", WW + "qwldatadevicemanager.cpp",
         WW + "qwldatasource.cpp", WW + "qwldataoffer.cpp"]

orig = tempfile.mkdtemp()
for f in files:
    shutil.copy(os.path.join(src, f), os.path.join(orig, os.path.basename(f)))

def edit(rel, pairs):
    p = os.path.join(src, rel)
    s = open(p).read()
    for old, new in pairs:
        assert old in s, (rel, old)
        s = s.replace(old, new, 1)
    open(p, "w").write(s)

edit(CA + "qwaylandseat.cpp", [
    ("d->init(d->compositor->display(), 4);", "d->init(d->compositor->display(), 5);"),
    ("data_device->add(client, id, 1);", "data_device->add(client, id, 3);")])
edit(WW + "qwldatadevicemanager.cpp", [
    (": wl_data_device_manager(compositor->display(), 1)", ": wl_data_device_manager(compositor->display(), 3)")])
edit(WW + "qwldatasource.cpp", [
    (": QtWaylandServer::wl_data_source(client, id, 1)", ": QtWaylandServer::wl_data_source(client, id, 3)")])
edit(WW + "qwldataoffer.cpp", [
    (": QtWaylandServer::wl_data_offer(target->client(), 0, 1)", ": QtWaylandServer::wl_data_offer(target->client(), 0, 3)")])

frame = '''QT_BEGIN_NAMESPACE

// wl_pointer >= 5 groups events with frame; wl_seat is bound at 5 (mylinux patch), so emit frames.
static inline void sendPointerFrame(QtWaylandServer::wl_pointer *p, struct ::wl_resource *r)
{
    if (wl_resource_get_version(r) >= 5)
        p->send_frame(r);
}
'''
def loop(old_call, obj):
    """Wrap a one-line for-loop body in braces and add a frame send."""
    return (old_call, old_call.replace("))\n        ", ")) {\n        ", 1).rstrip("\n")
            + "\n        sendPointerFrame(%s, resource->handle);\n    }\n" % obj)

edit(CA + "qwaylandpointer.cpp", [
    ("QT_BEGIN_NAMESPACE\n", frame),
    loop("    for (auto resource : resourceMap().values(client))\n"
         "        send_button(resource->handle, serial, time, q->toWaylandButton(button), state);\n", "this"),
    loop("    for (auto resource : resourceMap().values(enteredSurface->waylandClient()))\n"
         "        wl_pointer_send_motion(resource->handle, time, x, y);\n", "this"),
    loop("    for (auto resource : resourceMap().values(surface->waylandClient()))\n"
         "        send_enter(resource->handle, enterSerial, surface->resource(), x, y);\n", "this"),
    loop("    for (auto resource : resourceMap().values(enteredSurface->waylandClient()))\n"
         "        send_leave(resource->handle, serial, enteredSurface->resource());\n", "this"),
    loop("    for (auto resource : d->resourceMap().values(d->enteredSurface->waylandClient()))\n"
         "        d->send_axis(resource->handle, time, axis, wl_fixed_from_int(-delta / 12));\n", "d"),
    ("                      wl_fixed_from_double(d->localPosition.y()));\n    }\n",
     "                      wl_fixed_from_double(d->localPosition.y()));\n        sendPointerFrame(d, resource);\n    }\n"),
    ("    d->send_button(resource, serial, time, toWaylandButton(button), state);\n    return serial;\n",
     "    d->send_button(resource, serial, time, toWaylandButton(button), state);\n    sendPointerFrame(d, resource);\n    return serial;\n"),
])

header = """compositor: wl_seat v5 (+pointer frame events) and wl_data_device_manager v3

Qt binds wl_seat at version 4 and wl_data_device_manager at 1. Modern clients
(foot, GTK4, SDL3) require seat >= 5 and foot treats a data device manager
below 3 as fatal. Seat 5 only adds wl_pointer.frame/axis_* events: emit a frame
after every pointer event group. Data device manager 3 adds drag-and-drop
actions whose requests the generated code already accepts as no-ops; bump the
manager, source, offer and device objects to 3.

mylinux local patch, not upstream. Generated by tools/gen-qt6wayland-patch.py.

"""
body = ""
for f in files:
    r = subprocess.run(["diff", "-u", os.path.join(orig, os.path.basename(f)), os.path.join(src, f)],
                       capture_output=True, text=True)
    lines = r.stdout.splitlines(True)
    lines[0] = "--- a/%s\n" % f
    lines[1] = "+++ b/%s\n" % f
    body += "".join(lines)
os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, "w").write(header + body)
print("wrote", os.path.abspath(out), body.count("\n@@"), "hunks")
